#!/usr/bin/env python3
"""Prepare compact raw holds and correction measurements for REAPER.

The original recordings are never modified.  Every output label has the same
sample length as its source label.  REAPER projects generated by the companion
renderer use the same layout so detector results can be compared directly.
"""

from __future__ import annotations

import argparse
import binascii
import dataclasses
import hashlib
import json
import math
import pathlib
import struct
from typing import BinaryIO, Iterable

import numpy as np
from scipy import signal


M3_OPEN_NOTES = (32, 36, 40, 44, 48, 52, 56, 60)


@dataclasses.dataclass(frozen=True)
class ReplayLabel:
    start_sample: int
    end_sample: int
    midi_note: int
    string_mask: int
    calibration_pass: int
    expected_cents: float | None = None


@dataclasses.dataclass(frozen=True)
class WaveLayout:
    path: pathlib.Path
    sample_rate: int
    sample_count: int
    data_offset: int


def _read_exact(stream: BinaryIO, size: int) -> bytes:
    value = stream.read(size)
    if len(value) != size:
        raise ValueError("truncated WAV")
    return value


def inspect_float_wave(path: pathlib.Path) -> WaveLayout:
    path = pathlib.Path(path)
    with path.open("rb") as stream:
        header = _read_exact(stream, 12)
        if header[:4] != b"RIFF" or header[8:] != b"WAVE":
            raise ValueError("not a RIFF/WAVE file")
        fmt = None
        data = None
        while True:
            chunk_header = stream.read(8)
            if not chunk_header:
                break
            if len(chunk_header) != 8:
                raise ValueError("truncated WAV chunk header")
            chunk_id, chunk_size = struct.unpack("<4sI", chunk_header)
            chunk_offset = stream.tell()
            if chunk_id == b"fmt ":
                payload = _read_exact(stream, chunk_size)
                if len(payload) < 16:
                    raise ValueError("short WAV fmt chunk")
                fmt = struct.unpack_from("<HHIIHH", payload)
            elif chunk_id == b"data":
                data = (chunk_offset, chunk_size)
                stream.seek(chunk_size, 1)
            else:
                stream.seek(chunk_size, 1)
            if chunk_size & 1:
                stream.seek(1, 1)
        if fmt is None or data is None:
            raise ValueError("WAV is missing fmt or data")
        encoding, channels, sample_rate, _, block_align, bits = fmt
        if (encoding, channels, bits, block_align) != (3, 1, 32, 4):
            raise ValueError("expected mono IEEE-float32 WAV")
        if data[1] % 4 != 0:
            raise ValueError("unaligned float32 WAV data")
        return WaveLayout(path, sample_rate, data[1] // 4, data[0])


def map_float_wave(path: pathlib.Path) -> tuple[np.memmap, int]:
    layout = inspect_float_wave(path)
    samples = np.memmap(
        layout.path,
        mode="r",
        dtype="<f4",
        offset=layout.data_offset,
        shape=(layout.sample_count,),
    )
    return samples, layout.sample_rate


def read_float_wave(path: pathlib.Path) -> tuple[np.ndarray, int]:
    samples, sample_rate = map_float_wave(path)
    return np.asarray(samples, dtype=np.float32).copy(), sample_rate


class _FloatWaveWriter:
    def __init__(self, path: pathlib.Path, sample_rate: int, sample_count: int):
        self.path = pathlib.Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.sample_rate = int(sample_rate)
        self.sample_count = int(sample_count)
        self.written = 0
        data_size = self.sample_count * 4
        if data_size > 0xFFFFFFFF - 36:
            raise ValueError("WAV exceeds RIFF32 size")
        self.stream = self.path.open("wb")
        self.stream.write(
            struct.pack(
                "<4sI4s4sIHHIIHH4sI",
                b"RIFF",
                36 + data_size,
                b"WAVE",
                b"fmt ",
                16,
                3,
                1,
                self.sample_rate,
                self.sample_rate * 4,
                4,
                32,
                b"data",
                data_size,
            )
        )

    def write(self, samples: np.ndarray) -> None:
        block = np.asarray(samples, dtype="<f4")
        if block.ndim != 1 or self.written + len(block) > self.sample_count:
            raise ValueError("invalid WAV output block")
        self.stream.write(block.tobytes())
        self.written += len(block)

    def close(self) -> None:
        try:
            if self.written != self.sample_count:
                raise ValueError("incomplete WAV output")
        finally:
            self.stream.close()

    def __enter__(self) -> "_FloatWaveWriter":
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        if exc_type is None:
            self.close()
        else:
            self.stream.close()


def write_float_wave(
    path: pathlib.Path, samples: np.ndarray, sample_rate: int
) -> None:
    samples = np.asarray(samples, dtype=np.float32)
    with _FloatWaveWriter(path, sample_rate, len(samples)) as writer:
        writer.write(samples)


def read_labels(path: pathlib.Path) -> list[ReplayLabel]:
    lines = pathlib.Path(path).read_text(encoding="ascii").splitlines()
    five_columns = (
        "start_sample\tend_sample\tmidi_note\tstring_mask\tcalibration_pass"
    )
    six_columns = five_columns + "\texpected_cents"
    if not lines or lines[0] not in (five_columns, six_columns):
        raise ValueError("labels require the five- or six-column replay header")
    field_count = 6 if lines[0] == six_columns else 5
    labels = []
    for line in lines[1:]:
        if not line:
            continue
        fields = line.split("\t")
        if len(fields) != field_count:
            raise ValueError("invalid replay label")
        values = tuple(int(value) for value in fields[:5])
        expected_cents = None
        if field_count == 6:
            expected_cents = float(fields[5])
            if not math.isfinite(expected_cents) or not -50.0 <= expected_cents <= 50.0:
                raise ValueError("invalid expected cents")
        label = ReplayLabel(*values, expected_cents)
        if (
            label.start_sample < 0
            or label.end_sample <= label.start_sample
            or not 0 <= label.midi_note <= 127
            or not 1 <= label.string_mask <= 255
            or not 1 <= label.calibration_pass <= 255
        ):
            raise ValueError("invalid replay label value")
        labels.append(label)
    if not labels:
        raise ValueError("empty replay label file")
    return labels


def _write_labels(path: pathlib.Path, labels: Iterable[ReplayLabel]) -> None:
    labels = list(labels)
    has_expected = [label.expected_cents is not None for label in labels]
    if any(has_expected) and not all(has_expected):
        raise ValueError("expected cents must be present on every label or none")
    header = (
        "start_sample\tend_sample\tmidi_note\tstring_mask\tcalibration_pass"
    )
    if all(has_expected) and labels:
        header += "\texpected_cents"
    rows = [header]
    for label in labels:
        row = (
            f"{label.start_sample}\t{label.end_sample}\t{label.midi_note}\t"
            f"{label.string_mask}\t{label.calibration_pass}"
        )
        if label.expected_cents is not None:
            row += f"\t{label.expected_cents:.6f}"
        rows.append(row)
    pathlib.Path(path).write_text("\n".join(rows) + "\n", encoding="ascii")


def midi_frequency(midi_note: int, a4_hz: float = 440.0) -> float:
    return a4_hz * math.pow(2.0, (midi_note - 69) / 12.0)


def estimate_pitch_hz(
    samples: np.ndarray,
    sample_rate: int,
    nominal_hz: float,
    search_cents: float = 80.0,
) -> float:
    """Estimate a known note's fundamental with bounded autocorrelation."""
    values = np.asarray(samples, dtype=np.float64)
    if values.ndim != 1 or len(values) < 1024:
        raise ValueError("pitch segment is too short")
    maximum = min(len(values), int(round(sample_rate * 0.9)))
    start = max(0, (len(values) - maximum) // 2)
    values = values[start : start + maximum]
    # Retain roughly 96 samples per nominal period.  A fixed 24 kHz working
    # rate is adequate for bass notes but quantizes high-fret lag estimates by
    # several cents, which is large enough to manufacture a false correction.
    rate_decimation = max(1, sample_rate // 24_000)
    pitch_decimation = max(1, int(sample_rate / (nominal_hz * 96.0)))
    decimation = min(rate_decimation, pitch_decimation)
    if decimation > 1:
        values = signal.resample_poly(values, 1, decimation)
    working_rate = sample_rate / decimation
    values -= float(np.mean(values))
    rms = math.sqrt(float(np.mean(values * values)))
    if not math.isfinite(rms) or rms < 1.0e-5:
        raise ValueError("pitch segment has insufficient energy")
    values *= np.hanning(len(values))
    correlation = signal.fftconvolve(values, values[::-1], mode="full")
    correlation = correlation[len(values) - 1 :]
    highest = nominal_hz * math.pow(2.0, search_cents / 1200.0)
    lowest = nominal_hz / math.pow(2.0, search_cents / 1200.0)
    low_lag = max(1, int(math.floor(working_rate / highest)))
    high_lag = min(
        len(correlation) - 2, int(math.ceil(working_rate / lowest))
    )
    if low_lag >= high_lag:
        raise ValueError("pitch search range is empty")
    lag = low_lag + int(np.argmax(correlation[low_lag : high_lag + 1]))
    left, center, right = correlation[lag - 1 : lag + 2]
    denominator = left - 2.0 * center + right
    fraction = 0.0 if abs(denominator) < 1.0e-20 else 0.5 * (left - right) / denominator
    refined_lag = lag + float(np.clip(fraction, -0.5, 0.5))
    estimate = working_rate / refined_lag
    if not math.isfinite(estimate) or estimate <= 0.0:
        raise ValueError("invalid pitch estimate")
    return estimate


def _sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with pathlib.Path(path).open("rb") as stream:
        while block := stream.read(1024 * 1024):
            digest.update(block)
    return digest.hexdigest()


def _calibration_image(path: pathlib.Path) -> bytearray:
    data = bytearray(pathlib.Path(path).read_bytes())
    header_size = 24
    point_size = 19
    point_count = 8 * 25
    expected_size = header_size + 1 + point_count * point_size
    if (
        len(data) != expected_size
        or data[:4] != b"M3CB"
        or struct.unpack_from("<HHHHI", data, 4) != (1, 8, 25, 6, 3801)
        or struct.unpack_from("<I", data, 16)[0]
        != (binascii.crc32(data[header_size:]) & 0xFFFFFFFF)
    ):
        raise ValueError("invalid M3CB calibration image")
    return data


def _write_calibration_image(data: bytearray, output_path: pathlib.Path) -> None:
    struct.pack_into(
        "<I", data, 16, binascii.crc32(data[24:]) & 0xFFFFFFFF
    )
    output_path = pathlib.Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(data)


def write_adjusted_center_calibration(
    source_path: pathlib.Path,
    output_path: pathlib.Path,
    cents_scale: float = 1.0,
    cents_offset: float = 0.0,
) -> None:
    """Adjust pitch centers while retaining measured timbre/repeatability."""
    if not math.isfinite(cents_scale) or not 0.0 <= cents_scale <= 1.0:
        raise ValueError("cents scale must be in 0..1")
    if not math.isfinite(cents_offset) or not -50.0 <= cents_offset <= 50.0:
        raise ValueError("cents offset must be in -50..50")
    data = _calibration_image(source_path)
    point_size = 19
    point_count = 8 * 25
    first_point = 25
    offset_q8 = round(cents_offset * 256.0)
    for point in range(point_count):
        offset = first_point + point * point_size
        if data[offset + point_size - 1] == 0:
            continue
        cents_q8 = struct.unpack_from("<h", data, offset)[0]
        adjusted_q8 = round(cents_q8 * cents_scale) + offset_q8
        if not -50 * 256 <= adjusted_q8 <= 50 * 256:
            raise ValueError("adjusted pitch center exceeds M3CB range")
        struct.pack_into("<h", data, offset, adjusted_q8)
    _write_calibration_image(data, output_path)


def write_scaled_center_calibration(
    source_path: pathlib.Path,
    output_path: pathlib.Path,
    cents_scale: float,
) -> None:
    write_adjusted_center_calibration(
        source_path, output_path, cents_scale=cents_scale
    )


def write_note_shuffled_center_calibration(
    source_path: pathlib.Path, output_path: pathlib.Path
) -> None:
    """Rotate pitch centers between strings that can play the same MIDI note."""
    data = _calibration_image(source_path)
    point_size = 19
    by_note: dict[int, list[int]] = {}
    for string_index, open_note in enumerate(M3_OPEN_NOTES):
        for fret in range(25):
            by_note.setdefault(open_note + fret, []).append(string_index * 25 + fret)
    for points in by_note.values():
        points = [
            point
            for point in points
            if data[25 + point * point_size + point_size - 1] != 0
        ]
        if len(points) < 2:
            continue
        centers = [
            struct.unpack_from("<h", data, 25 + point * point_size)[0]
            for point in points
        ]
        for point, cents_q8 in zip(points, centers[1:] + centers[:1]):
            struct.pack_into("<h", data, 25 + point * point_size, cents_q8)
    _write_calibration_image(data, output_path)


def write_expected_cents_labels(
    source_labels: pathlib.Path,
    manifest_path: pathlib.Path,
    output_path: pathlib.Path,
    residual_fraction: float,
    truth_calibration: pathlib.Path | None = None,
) -> None:
    """Attach pitch truth from a manifest or one frozen scoring bank."""
    if not math.isfinite(residual_fraction) or not 0.0 <= residual_fraction <= 1.0:
        raise ValueError("residual fraction must be in 0..1")
    labels = read_labels(source_labels)
    manifest = json.loads(pathlib.Path(manifest_path).read_text(encoding="utf-8"))
    observations = manifest.get("observations")
    if not isinstance(observations, list) or len(observations) != len(labels):
        raise ValueError("manifest observations do not match labels")
    centers = None
    string_index = manifest.get("string_index")
    if truth_calibration is not None:
        if not isinstance(string_index, int) or not 0 <= string_index < 8:
            raise ValueError("manifest has no valid string index")
        data = _calibration_image(truth_calibration)
        centers = [
            struct.unpack_from("<h", data, 25 + point * 19)[0] / 256.0
            for point in range(8 * 25)
        ]
    enriched = []
    for label, observation in zip(labels, observations):
        if not isinstance(observation, dict):
            raise ValueError("invalid manifest observation")
        measured = observation.get("measured_cents_from_target")
        if not isinstance(measured, (int, float)) or not math.isfinite(measured):
            raise ValueError("manifest observation has no finite cents value")
        expected = float(measured)
        if centers is not None:
            fret = label.midi_note - M3_OPEN_NOTES[string_index]
            if not 0 <= fret < 25:
                raise ValueError("label note is outside the string range")
            expected = centers[string_index * 25 + fret]
        expected *= residual_fraction
        if not -50.0 <= expected <= 50.0:
            raise ValueError("expected cents exceeds replay label range")
        enriched.append(dataclasses.replace(label, expected_cents=expected))
    _write_labels(output_path, enriched)


def write_zero_centered_calibration(
    source_path: pathlib.Path, output_path: pathlib.Path
) -> None:
    write_scaled_center_calibration(source_path, output_path, 0.0)


def generate_string_corpus(
    source_wave: pathlib.Path,
    source_labels: pathlib.Path,
    output_directory: pathlib.Path,
    string_index: int,
    silence_seconds: float = 0.25,
    a4_hz: float = 440.0,
) -> dict[str, object]:
    if not 0 <= string_index < 8:
        raise ValueError("string index must be in 0..7")
    source, sample_rate = map_float_wave(source_wave)
    labels = read_labels(source_labels)
    if labels[-1].end_sample > len(source):
        raise ValueError("label exceeds source WAV")
    expected_mask = 1 << string_index
    if any(label.string_mask != expected_mask for label in labels):
        raise ValueError("label string mask does not match string index")
    silence_frames = int(round(sample_rate * silence_seconds))
    if silence_frames < 0:
        raise ValueError("negative silence duration")
    output_samples = sum(
        label.end_sample - label.start_sample for label in labels
    ) + silence_frames * (len(labels) + 1)
    output_directory = pathlib.Path(output_directory)
    output_directory.mkdir(parents=True, exist_ok=True)
    physical_string_number = 8 - string_index
    stem = f"string-{physical_string_number:02d}"
    raw_path = output_directory / f"{stem}-raw.wav"
    labels_path = output_directory / f"{stem}.tsv"
    silence = np.zeros(silence_frames, dtype=np.float32)
    output_labels: list[ReplayLabel] = []
    observations = []
    cursor = silence_frames
    with _FloatWaveWriter(raw_path, sample_rate, output_samples) as raw_writer:
        raw_writer.write(silence)
        for index, label in enumerate(labels):
            segment = np.asarray(
                source[label.start_sample : label.end_sample], dtype=np.float32
            )
            target_hz = midi_frequency(label.midi_note, a4_hz)
            measured_hz = estimate_pitch_hz(segment, sample_rate, target_hz)
            measured_cents = 1200.0 * math.log2(measured_hz / target_hz)
            raw_writer.write(segment)
            output_labels.append(
                ReplayLabel(
                    cursor,
                    cursor + len(segment),
                    label.midi_note,
                    label.string_mask,
                    label.calibration_pass,
                    measured_cents,
                )
            )
            observations.append(
                {
                    "label_index": index,
                    "midi_note": label.midi_note,
                    "calibration_pass": label.calibration_pass,
                    "source_start_sample": label.start_sample,
                    "source_end_sample": label.end_sample,
                    "target_hz": target_hz,
                    "measured_hz": measured_hz,
                    "measured_cents_from_target": measured_cents,
                    "pitch_correction_semitones": 12.0
                    * math.log2(target_hz / measured_hz),
                }
            )
            cursor += len(segment)
            raw_writer.write(silence)
            cursor += silence_frames
    _write_labels(labels_path, output_labels)
    manifest = {
        "schema": 1,
        "correction_plan": "reaper-elastique-3-pro-v1",
        "a4_hz": a4_hz,
        "sample_rate_hz": sample_rate,
        "string_index": string_index,
        "physical_string_number": physical_string_number,
        "string_mask": expected_mask,
        "label_count": len(labels),
        "silence_frames_between_holds": silence_frames,
        "output_sample_count": output_samples,
        "source_wave": str(pathlib.Path(source_wave).resolve()),
        "source_labels": str(pathlib.Path(source_labels).resolve()),
        "source_wave_sha256": _sha256(source_wave),
        "source_labels_sha256": _sha256(source_labels),
        "raw_wave": raw_path.name,
        "raw_wave_sha256": _sha256(raw_path),
        "labels": labels_path.name,
        "labels_sha256": _sha256(labels_path),
        "observations": observations,
    }
    manifest_path = output_directory / f"{stem}-manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        action="append",
        nargs=3,
        metavar=("STRING_INDEX", "WAV", "LABELS"),
        required=True,
        help="zero-based string index, source WAV, and five-column labels",
    )
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--silence-ms", type=float, default=250.0)
    parser.add_argument("--a4", type=float, default=440.0)
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    manifests = []
    for index_text, wave_text, labels_text in args.input:
        manifest = generate_string_corpus(
            pathlib.Path(wave_text),
            pathlib.Path(labels_text),
            args.output,
            int(index_text),
            silence_seconds=args.silence_ms / 1000.0,
            a4_hz=args.a4,
        )
        manifests.append(manifest)
        print(
            f"physical string {manifest['physical_string_number']} "
            f"(lane {index_text}): {manifest['label_count']} labels, "
            f"{manifest['output_sample_count']} samples"
        )
    aggregate = {
        "schema": 1,
        "correction_plan": "reaper-elastique-3-pro-v1",
        "a4_hz": args.a4,
        "strings": manifests,
    }
    (args.output / "manifest.json").write_text(
        json.dumps(aggregate, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
